site_name: Inkeep Demo Lib
site_description: A tiny TypeScript library with clean, crawlable docs for Inkeep demos.
site_url: https://<your-username>.github.io/inkeep-demo-lib/
repo_url: https://github.com/<your-username>/inkeep-demo-lib
theme:
  name: material
  features:
    - content.code.copy
    - navigation.instant
    - navigation.sections
    - search.suggest
plugins:
  - search
nav:
  - Home: index.md
  - Guides:
      - Quickstart: guides/quickstart.md
      - Usage Patterns: guides/usage-patterns.md
  - API Reference:
      - Overview: api/modules.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/<your-username>/inkeep-demo-lib
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
extra_css:
  - assets/extra.css
