name: Build & Deploy Docs

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node deps
        run: npm ci

      - name: Generate API docs (TypeDoc -> Markdown)
        run: npm run build:typedoc

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MkDocs Material
        run: pip install mkdocs-material

      - name: Build & Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
